### ISSUE TITLE
ComfyUI Implementation

### ISSUE THREAD

**Issue by Veilosity** [Kazuhito00/Skin-Clothes-Hair-Segmentation-using-SMP#1]
This model does a good job of segmenting skin in ComfyUI, but is there a way to use it for clothes and hair as well?

**Comment by Kazuhito00** [comment]
This model allows segmentation using the following classes.
　Class ID 1：Skin
　Class ID 2：Clothes
　Class ID 3：Hair

**Comment by Veilosity** [comment]
I know that; I was just wondering how I can select different class IDs.

**Comment by Kazuhito00** [comment]
Please check the sample script.
mask has a list structure.
https://github.com/Kazuhito00/Skin-Clothes-Hair-Segmentation-using-SMP/blob/043fc08bf0ed845b36485a115085104c6459cbc4/demo_onnx_simple.py#L207C13-L207C18

**Comment by Veilosity** [comment]
I'm using the model in Comfyui, so I'm wondering how to select the options for clothes and/or hair since the default appears to be skin. If there isn't any way to use the other modes in Comfyui, maybe you could do a separate model for each mode rather than bundling them all together.
